//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(MAS_PriceMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_Food))]
    public partial class MAS_Price : BusinessEntityBase
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int PriceId { get; set; }
        [DataMember]
        public int FoodId { get; set; }
        [DataMember]
        public string Price { get; set; }
        [DataMember]
        public string GSTPrice { get; set; }
        [DataMember]
        public string GSTPercentage { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual MAS_Food MAS_Food { get; set; }
    }

}
