//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(MAS_PaymentTypeMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(TRN_Order))]
    public partial class MAS_PaymentType  :BusinessEntityBase 
    {
    public MAS_PaymentType()
    {
    this.TRN_Order = new HashSet<TRN_Order>();
    }
    
    [DataMember]
    public System.Guid UniqueId { get; set; }
    [DataMember]
    [Key]
    public int PaymentTypeId { get; set; }
    [DataMember]
    public string PaymentType { get; set; }
    [DataMember]
    public bool IsDeleted { get; set; }
    
    [DataMember]
    public virtual ICollection<TRN_Order> TRN_Order { get; set; }
    }
    
}
