//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(MAS_DiscountTypeMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_Discount))]
    [KnownType(typeof(TRN_SpecialDiscount))]
    public partial class MAS_DiscountType : BusinessEntityBase
    {
        public MAS_DiscountType()
        {
            this.MAS_Discount = new HashSet<MAS_Discount>();
            this.TRN_SpecialDiscount = new HashSet<TRN_SpecialDiscount>();
        }

        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int DiscountTypeID { get; set; }
        [DataMember]
        public string DiscountType { get; set; }
        [DataMember]
        public string Descriptions { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual ICollection<MAS_Discount> MAS_Discount { get; set; }
        [DataMember]
        public virtual ICollection<TRN_SpecialDiscount> TRN_SpecialDiscount { get; set; }
    }

}
