//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(MAS_CategoryMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_Food))]
    public partial class MAS_Category : BusinessEntityBase
    {
        public MAS_Category()
        {
            this.MAS_Food = new HashSet<MAS_Food>();
        }

        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int CategoryId { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Descriptions { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual ICollection<MAS_Food> MAS_Food { get; set; }
    }

}
