//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(TRN_UserAddressDetailsMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_AddressType))]
    [KnownType(typeof(MAS_City))]
    [KnownType(typeof(MAS_DeliveryLocation))]
    [KnownType(typeof(TRN_DeliveryDetails))]
    [KnownType(typeof(TRN_UserDetail))]
    public partial class TRN_UserAddressDetails : BusinessEntityBase
    {
        public TRN_UserAddressDetails()
        {
            this.TRN_DeliveryDetails = new HashSet<TRN_DeliveryDetails>();
        }

        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int AddressDetailId { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public int AddressTypeID { get; set; }
        [DataMember]
        public int DeliveryPointId { get; set; }
        [DataMember]
        public string AreaName { get; set; }
        [DataMember]
        public string AddressLine1 { get; set; }
        [DataMember]
        public string AddressLine2 { get; set; }
        [DataMember]
        public int CityId { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual MAS_AddressType MAS_AddressType { get; set; }
        [DataMember]
        public virtual MAS_City MAS_City { get; set; }
        [DataMember]
        public virtual MAS_DeliveryLocation MAS_DeliveryLocation { get; set; }
        [DataMember]
        public virtual ICollection<TRN_DeliveryDetails> TRN_DeliveryDetails { get; set; }
        [DataMember]
        public virtual TRN_UserDetail TRN_UserDetail { get; set; }
    }

}
