//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(TRN_ChefOrderMetadata))]
    [DataContract(IsReference = true)]
    public partial class TRN_ChefOrder : BusinessEntityBase
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int ChefOrderId { get; set; }
        [DataMember]
        public System.DateTime OrderGivenDatetime { get; set; }
        [DataMember]
        public System.TimeSpan ChefDeliveredDateTime { get; set; }
        [DataMember]
        public System.DateTime AssignedPickUpDate { get; set; }
        [DataMember]
        public System.TimeSpan AssignedPickUpTime { get; set; }
        [DataMember]
        public int TaskStatusID { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
    }

}
