//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(TRN_DeliveryDetailsMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_DeliveryLocation))]
    [KnownType(typeof(TRN_UserAddressDetails))]
    [KnownType(typeof(TRN_Order))]
    public partial class TRN_DeliveryDetails : BusinessEntityBase
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int DeliveryDetailId { get; set; }
        [DataMember]
        public int OrderId { get; set; }
        [DataMember]
        public System.DateTime OrderDate { get; set; }
        [DataMember]
        public System.DateTime ScheduleDeliveryDate { get; set; }
        [DataMember]
        public Nullable<bool> IsDelivered { get; set; }
        [DataMember]
        public int DeliveryPointId { get; set; }
        [DataMember]
        public int AddressDetailId { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual MAS_DeliveryLocation MAS_DeliveryLocation { get; set; }
        [DataMember]
        public virtual TRN_UserAddressDetails TRN_UserAddressDetails { get; set; }
        [DataMember]
        public virtual TRN_Order TRN_Order { get; set; }
    }

}
