//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(TRN_LoginDetailMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(TRN_UserDetail))]
    public partial class TRN_LoginDetail : BusinessEntityBase
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int LoginId { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public string LoginName { get; set; }
        [DataMember]
        public string EmailId { get; set; }
        [DataMember]
        public string PhoneNo { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual TRN_UserDetail TRN_UserDetail { get; set; }
    }

}
