//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [Microsoft.AspNetCore.Mvc.ModelMetadataType(typeof(TRN_OrderAppliedDiscountMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_Discount))]
    [KnownType(typeof(TRN_Order))]
    [KnownType(typeof(TRN_SpecialDiscount))]
    public partial class TRN_OrderAppliedDiscount : BusinessEntityBase
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        [Key]
        public int AppliedDiscountId { get; set; }
        [DataMember]
        public int DiscountId { get; set; }
        [DataMember]
        public int SpecialDiscountId { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
        [DataMember]
        public int OrderId { get; set; }

        [DataMember]
        public virtual MAS_Discount MAS_Discount { get; set; }
        [DataMember]
        public virtual TRN_Order TRN_Order { get; set; }
        [DataMember]
        public virtual TRN_SpecialDiscount TRN_SpecialDiscount { get; set; }
    }

}
