//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetCore.Business.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class MAS_MealPackDto
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        public int MealPackId { get; set; }
        [DataMember]
        public string MealPackName { get; set; }
        [DataMember]
        public string Descriptions { get; set; }
        [DataMember]
        public int TotalMealCount { get; set; }
        [DataMember]
        public int CurrentMealCount { get; set; }
        [DataMember]
        public int CurrentPrice { get; set; }
        [DataMember]
        public int TotalPrice { get; set; }
        [DataMember]
        public int GSTPrice { get; set; }
        [DataMember]
        public int GSTPercentage { get; set; }
        [DataMember]
        public int OrderTypeId { get; set; }
        [DataMember]
        public Nullable<int> OrderTypeCode { get; set; }
        [DataMember]
        [JsonIgnore]
        public bool IsDeleted { get; set; }
      
    }
}
