//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetCore.Business.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class TRN_DeliveryDetailsDto
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        public int DeliveryDetailId { get; set; }
        [DataMember]
        public int OrderId { get; set; }
        [DataMember]
        public System.DateTime OrderDate { get; set; }
        [DataMember]
        public System.DateTime ScheduleDeliveryDate { get; set; }
        [DataMember]
        public Nullable<bool> IsDelivered { get; set; }
        [DataMember]
        public int DeliveryPointId { get; set; }
        [DataMember]
        public int AddressDetailId { get; set; }
        [DataMember]
        [JsonIgnore]
        public bool IsDeleted { get; set; }
       }
}
