//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetCore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class TRN_MapOrderToChefDto
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        public int MapOrderID { get; set; }
        [DataMember]
        public int OrderId { get; set; }
        [DataMember]
        public int ChefId { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
   
    }
}
