//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetCore.Business.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class TRN_MealPackProcessingDto
    {
        [DataMember]
        public System.Guid UniqueId { get; set; }
        [DataMember]
        public int MealPackProcessingId { get; set; }
        [DataMember]
        public int MealPackId { get; set; }
        [DataMember]
        public int TotalMealCount { get; set; }
        [DataMember]
        public int UsedMealCount { get; set; }
        [DataMember]
        public int RemainingMealCount { get; set; }
        [DataMember]
        public System.DateTime ScheduleDates { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public int OrderId { get; set; }
        [DataMember]
        [JsonIgnore]
        public bool IsDeleted { get; set; }
    }
}
